#!/bin/sh

fd --type file .webp equipment/hat equipment/cloak equipment/amulet equipment/ring equipment/belt equipment/boots weapons equipment/shield |
kak -f '<a-s>_yi![<c-r>"](<esc>a)<esc>O######<space>[`<c-r>"`](<c-r>")'
